name: Fetch Data

# on:
#  push:
#    branches:
#    - master

# the workflow runs exactly 48 hours before the next deadline date
# for example, the deadline for gameweek 17 is 14 Dec 2019 11:30 UTC
# so the workflow will execute on 12 Dec 2019 11:30 UTC
on:
   schedule:
   - cron: '30 03 12 08 *'
   - cron: '00 07 20 08 *'
   - cron: '30 03 26 08 *'
   - cron: '30 03 02 09 *'
   - cron: '00 07 17 09 *'
   - cron: '30 03 23 09 *'
   - cron: '00 07 01 10 *'
   - cron: '30 03 07 10 *'
   - cron: '00 07 22 10 *'
   - cron: '30 04 28 10 *'
   - cron: '30 04 04 11 *'
   - cron: '30 04 11 11 *'
   - cron: '00 08 26 11 *'
   - cron: '30 04 02 12 *'
   - cron: '15 08 06 12 *'
   - cron: '00 08 10 12 *'
   - cron: '45 07 17 12 *'
   - cron: '30 04 23 12 *'
   - cron: '45 07 28 12 *'
   - cron: '00 06 30 12 *'
   - cron: '00 08 03 01 *'
   - cron: '30 04 13 01 *'
   - cron: '30 04 20 01 *'
   - cron: '00 08 24 01 *'
   - cron: '00 03 02 02 *'
   - cron: '00 03 09 02 *'
   - cron: '00 03 23 02 *'
   - cron: '00 02 02 03 *'
   - cron: '00 08 10 03 *'
   - cron: '00 08 17 03 *'
   - cron: '30 04 23 03 *'
   - cron: '00 07 07 04 *'
   - cron: '00 07 14 04 *'
   - cron: '00 07 21 04 *'
   - cron: '00 07 28 04 *'
   - cron: '00 02 03 05 *'
   - cron: '00 02 10 05 *'
   - cron: '00 02 18 05 *'

jobs:
  fetchData:
    
    env:
      REMOTE_BRANCH: master

    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v1
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.x'
    
    - name: Install PIP packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch and organize data
      run: |
        python global_scraper.py
        python understat.py

      # change this config settings according to your need
    - name: Configure Git
      run: |
        git config --global user.email ${GITHUB_ACTOR}@gmail.com
        git config --global user.name ${GITHUB_ACTOR}
    
    - name: Commit and Push
      run: |
        gameweek_id=`python gameweek.py`
        git add data/2019-20
        git commit -m "gh-actions added gw${gameweek_id} data"
        git push --force https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git HEAD:${REMOTE_BRANCH}
